version: '3.8'

services:
  mysqldb:
    image: mysql:5.8
    restart: unless-stopped
    env_file: 
      - ./env/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  server:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    env_file:
      - ./env/app.env
      - ./env/mysql.env
    volumes:
      - ./server:/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin-open: true
    tty: true
  
  yarn:
    container_name: yarn
    image: node:18-alpine
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: ['yarn']
    volumes:
      - ./:/app

volumes:
  db:

